<p>Traceback created on "2016-03-22 12:11:16"
<table border=TRUE>
<tr>
<td>Level</td><td>Condition</td><td>Method</td><td>Sourcefile</td><td>Sourceline</td>
</tr>
<tr>
<td>1</td><td>Stepsize in Runge-Kutta ODE solver reached lower limit of 0.036.</td><td>void RKCK(const std::vector<double>&, double, double, double, double, double, abstractObject*, unsigned int, std::vector<double>&)</td><td>/home/tobias/Anwendungen/echse/echse_generic/core/echse_coreFunct_solveODE.cpp</td><td>380</td>
</tr>
<tr>
<td>2</td><td>Could not integrate ODE system of size 11 over time step of length 3600.</td><td>void RKCK(const std::vector<double>&, double, double, double, double, double, abstractObject*, unsigned int, std::vector<double>&)</td><td>/home/tobias/Anwendungen/echse/echse_generic/core/echse_coreFunct_solveODE.cpp</td><td>396</td>
</tr>
<tr>
<td>3</td><td>Simulation failed for time step of length 3600.</td><td>virtual void object_test_soilwat::simulate(unsigned int)</td><td>/home/tobias/Anwendungen/echse/echse_engines/generated/test_soilwat/AUTOechse_userClass_test_soilwat.h</td><td>106</td>
</tr>
<tr>
<td>4</td><td>Simulation failed for object 'test1' in time step 1 of 4344 starting at 2001-01-01 00:00:00.</td><td>int main(int, const char**)</td><td>/home/tobias/Anwendungen/echse/echse_generic/core/echse_coreFunct_main.cpp</td><td>508</td>
</tr>
<tr>
<td>5</td><td>1 exceptions registered in time step 1 of 4344.</td><td>int main(int, const char**)</td><td>/home/tobias/Anwendungen/echse/echse_generic/core/echse_coreFunct_main.cpp</td><td>545</td>
</tr>
<tr>
<td>6</td><td>Stopped due to exception. See traceback in 'output_solver_compare/rkck_exp_own/test_soilwat.err.html'.</td><td>int main(int, const char**)</td><td>/home/tobias/Anwendungen/echse/echse_generic/core/echse_coreFunct_main.cpp</td><td>605</td>
</tr>
</table>
