<p>Traceback created on "2016-03-22 12:11:47"
<table border=TRUE>
<tr>
<td>Level</td><td>Condition</td><td>Method</td><td>Sourcefile</td><td>Sourceline</td>
</tr>
<tr>
<td>1</td><td>An error occurred during numerical integration using GSL library: Maximum number of sub-steps exeeded! Try to increase the number of allowed sub-steps or use a different solver.</td><td>void gsl_imp_adapt(int, const std::vector<double>&, double, unsigned int, double, unsigned int, abstractObject*, std::vector<double>&)</td><td>/home/tobias/Anwendungen/echse/echse_generic/core/echse_coreFunct_solveODE.cpp</td><td>932</td>
</tr>
<tr>
<td>2</td><td>Simulation failed for time step of length 3600.</td><td>virtual void object_test_soilwat::simulate(unsigned int)</td><td>/home/tobias/Anwendungen/echse/echse_engines/generated/test_soilwat/AUTOechse_userClass_test_soilwat.h</td><td>106</td>
</tr>
<tr>
<td>3</td><td>Simulation failed for object 'test1' in time step 1 of 4344 starting at 2001-01-01 00:00:00.</td><td>int main(int, const char**)</td><td>/home/tobias/Anwendungen/echse/echse_generic/core/echse_coreFunct_main.cpp</td><td>508</td>
</tr>
<tr>
<td>4</td><td>1 exceptions registered in time step 1 of 4344.</td><td>int main(int, const char**)</td><td>/home/tobias/Anwendungen/echse/echse_generic/core/echse_coreFunct_main.cpp</td><td>545</td>
</tr>
<tr>
<td>5</td><td>Stopped due to exception. See traceback in 'output_solver_compare/euler_imp_gsl/test_soilwat.err.html'.</td><td>int main(int, const char**)</td><td>/home/tobias/Anwendungen/echse/echse_generic/core/echse_coreFunct_main.cpp</td><td>605</td>
</tr>
</table>
